[terminal]
default_shell = "pwsh"

onboarding = false
[update]
channel = "preview"

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true

[ui.sound]
enabled = true

[experimental]
pane_history = true

[theme]
name = "tokyo-night"
auto_switch = false
